apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: meeting-server-viewer
  namespace: default
spec:
  rules:
  - services: ["meeting-server.default.svc.cluster.local"]
    methods: ["GET"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRoleBinding
metadata:
  name: meeting-server-viewer-binding
  namespace: default
spec:
  subjects:
  - user: "cluster.local/ns/default/sa/work-server"
  roleRef:
    kind: ServiceRole
    name: meeting-server-viewer
